name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          pip install black
          
      - name: Lint
        run: |
          black . --check --line-length=120 --exclude '(schema.py|setup.py|__init__.py|ec2_investigations)'
